### PR TITLE
Modify command for better readability

### PR DESCRIPTION
**Pull request by toyota790**
Fix typo for readme of [Service Bus Queue External Metric Scaling](https://github.com/Azure/azure-k8s-metrics-adapter/tree/master/samples/servicebus-queue)

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Just FYI, it's not a typo but an alias: https://github.com/ahmetb/kubectl-aliases

**Comment by toyota790** [comment]
@tomkerkhove Thank you for the information! I appreciate it! :)

**Comment by jsturtevant** [comment]
Thanks! I try not to use my aliases so this is a good improvement 👍

**Comment by toyota790** [comment]
@jsturtevant Anytime. Thanks for your approval.

**Pull request merged**
