### PR TITLE
Support sb topic subscriptions

### LINKED ISSUE #42: Add support for Service Bus Queue Topic Subscriptions
The primary External Metric provider uses Azure Monitor to gather metrics for the Service Bus Queues.  Service Bus only outputs total Metrics for a Queue Topic.  Using the GO [service bus library](https://github.com/Azure/azure-service-bus-go/blob/master/subscription.go#L56) we can query for the Subscription [value directly](https://github.com/Azure/azure-service-bus-go/blob/1912861e4166ab293c7ca0ac7d407d1b20a55a5e/subscription.go#L56).

### PR DESCRIPTION
**Pull request by jsturtevant**
Allow for users of the metrics adapter to gather message counts from Azure Service Bus Topic Subscriptions to decide their scaling targets

Closes #42

This replaces #49 which I didn't have permission to push updates too.  Thanks to @marc-sensenich for the initial implementation.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
We might want to add queues as well in a new PR

**Comment by paaland** [comment]
Can the pipleline be fixed so we can get this? Subscription message count is what I'm waiting for....

**Comment by tomkerkhove** [comment]
I don't like your motivation @azure-pipelines, try harder!

Also, it's not easy to configure this app correctly ☹️

**Comment by jsturtevant** [comment]
It seems that Azure devops does find the pipeline as it started to run.  Have not figured out why it sends that message.

Which app is not easy to configure?

**Comment by tomkerkhove** [comment]
I find the Azure Pipelines GitHub app not easy to setup, but that might just be me..

**Comment by aminebizid** [comment]
Any news guys

**Comment by aminebizid** [comment]
Hello,
I couldn't get the metrics using this PR:

### My External Metric
```yaml
apiVersion: azure.com/v1alpha2
kind: ExternalMetric
metadata:
  name: example-external-metric-service-bus-subscription
spec:
  type: servicebussubscription
  azure:
    resourceGroup: RG-TEST
    serviceBusNamespace: ttalogs
    serviceBusTopic: testk8s
    serviceBusSubscription: testk8ssub
  metric:
    # This would default to activeMessageCount, but could be updated to one of the counts from https://github.com/Azure/azure-sdk-for-go/blob/master/services/servicebus/mgmt/2017-04-01/servicebus/models.go#L1116
    metricName: activeMessageCount
```

### My HPA
```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
 name: consumer-scaler
spec:
 scaleTargetRef:
   apiVersion: extensions/v1beta1
   kind: Deployment
   name: consumer
 minReplicas: 1
 maxReplicas: 10
 metrics:
  - type: External
    external:
      metricName: activeMessageCount
      targetValue: 30
```

## Testing
```bash
kubectl -n hpa get hpa consumer-scaler -w
consumer-scaler   Deployment/consumer   <unknown>/30   1         10        1          20m

k -n azure-metrics logs -f azure-metrics-azure-k8s-metrics-adapter-6bb89f96fb-nbv8v
I0505 22:01:57.976022       1 provider_external.go:24] Received request for namespace: hpa, metric name: activemessagecount, metric selectors:
I0505 22:01:57.976060       1 metric_cache.go:41] metric not found ExternalMetric/hpa/activemessagecount
I0505 22:01:57.976082       1 metricrequest.go:104] Successfully parsed AzureMetric


kubectl get --raw /apis/azure.com/v1alpha2/namespaces/hpa/externalmetrics/example-external-metric-service-bus-subscription| jq
```

```json
{
  "apiVersion": "azure.com/v1alpha2",
  "kind": "ExternalMetric",
  "metadata": {
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"azure.com/v1alpha2\",\"kind\":\"ExternalMetric\",\"metadata\":{\"annotations\":{},\"name\":\"example-external-metric-service-bus-subscription\",\"namespace\":\"hpa\"},\"spec\":{\"azure\":{\"resourceGroup\":\"RG-DC-TTA-PROMETHEE\",\"serviceBusNamespace\":\"ttalogs\",\"serviceBusSubscription\":\"testk8ssub\",\"serviceBusTopic\":\"testk8s\"},\"metric\":{\"metricName\":\"ActiveMessageCount\"},\"type\":\"servicebussubscription\"}}\n"
    },
    "creationTimestamp": "2019-05-05T20:59:42Z",
    "generation": 2,
    "name": "example-external-metric-service-bus-subscription",
    "namespace": "hpa",
    "resourceVersion": "3697203",
    "selfLink": "/apis/azure.com/v1alpha2/namespaces/hpa/externalmetrics/example-external-metric-service-bus-subscription",
    "uid": "b41c2510-6f78-11e9-8ce8-000d3a48b4d9"
  },
  "spec": {
    "azure": {
      "resourceGroup": "RG-TEST",
      "serviceBusNamespace": "ttalogs",
      "serviceBusSubscription": "testk8ssub",
      "serviceBusTopic": "testk8s"
    },
    "metric": {
      "metricName": "ActiveMessageCount"
    },
    "type": "servicebussubscription"
  }
}
```

The Field "value" is not found

**Comment by jsturtevant** [comment]
@aminebizid You HPA `metricName` should reference the name of the External Metric which would be `example-external-metric-service-bus-subscription` instead of the metric name `activeMessageCount`

Additionally you should now check out the [KEDA](https://github.com/kedacore/keda) project for future work. Specifically [topic subscriptions](https://github.com/kedacore/keda/wiki/ScaledObject-spec#azure-service-bus-topics) are supported.

**Pull request merged**
